/totalRevenue:
  type:
    statistics-item:
      exampleItem: !include ../samples/totalRevenue.json
/totalOrders:
  type:
    statistics-item:
      exampleItem: !include ../samples/totalOrders.json
/totalCustomers:
  type:
    statistics-item:
      exampleItem: !include ../samples/totalCustomers.json
/mostOrdered:
  type:
    statistics-item:
      exampleItem: !include ../samples/mostOrdered.json
/mostTypeOfOrder:
  type:
    statistics-item:
      exampleItem: !include ../samples/mostTypeOfOrder.json