#%RAML 1.0
---
title: Jaegar Resto
baseUri: https://jaegar.resto.com/api{version}
version: v1

traits: !include traits/index.raml
resourceTypes: !include resourceTypes/index.raml

/dishes: !include resources/dishes.raml
/orders: !include resources/orders.raml
/statistics: !include resources/statistics.raml
/categories: !include resources/categories.raml
